### ISSUE TITLE
AmazonSQSExtendedClient does not have an implementation

### ISSUE THREAD

**Issue by mec2005** [raol/amazon-sqs-net-extended-client-lib#24]
Hi.
First of all I want to thank you for this solution.
I have an implementation that works fine, but when I updated AWSSDK.Core, AWSSDK.S3, AWSSDK.SimpleNotificationService and AWSSDK.SQS the client stopped working.

Now I have got the error.
```C#
System.TypeLoadException: 'Method 'get_Paginators' in type 'Amazon.SQS.ExtendedClient.AmazonSQSExtendedClient' from assembly 'Amazon.SQS.ExtendedClient, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
```
``` C#
try            
{
    _queueUrl = config.Url;
    _s3Client = new AmazonS3Client(new BasicAWSCredentials(config.AccessKey, config.SecretKey), Amazon.RegionEndpoint.GetBySystemName(config.Region));
    _sqsClient = new AmazonSQSClient(config.AccessKey, config.SecretKey, Amazon.RegionEndpoint.GetBySystemName(config.Region));
    _extendedClient = new AmazonSQSExtendedClient(_sqsClient, new ExtendedClientConfiguration().WithLargePayloadSupportEnabled(_s3Client, config.BucketName));
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "Constructor: SqsService");
        throw;
    }
}
```
I'll thank you again if help me!

**Comment by AshleyJButcher** [comment]
This problem relates to AWS SDK > 3.5.0

Rolling back to this version works for me

**Comment by jacobneroth** [comment]
ya looks like it breaking a few things in our system as well.

**Comment by erikdac** [comment]
Any plans to release a fix for this anytime soon? :)

**Comment by SimonGeorge-Zoopla** [comment]
https://github.com/raol/amazon-sqs-net-extended-client-lib/pull/38 fixes this issue

**Comment by Leuzi** [comment]
Hi! any way to get rid of this error at this point?

**Comment by rafael-herscovici-orielo** [comment]
New year, issue still exists.
Is there a plan to fix this? or should we look for alternatives?

`System.TypeLoadException: Method 'CancelMessageMoveTaskAsync' in type 'Amazon.SQS.ExtendedClient.AmazonSQSExtendedClient' from assembly 'Amazon.SQS.ExtendedClient, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)`

**Comment by raol** [comment]
Hi @rafael-herscovici-orielo could you please provide a project that replicates the problem?
